name: ✨ Feature Request
description: Suggest a new feature for the Focus On app
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 
        
        💡 **Tip**: Consider if this would be a good workshop issue and mention it below.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: What should this feature do?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this feature be useful?
      placeholder: Describe when and why someone would use this feature...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this should be implemented?
      placeholder: Describe your solution or any ideas you have...

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Easy (Good for beginners)
        - Medium (Some experience needed)
        - Hard (Advanced knowledge required)
        - Not sure

  - type: checkboxes
    id: workshop-suitable
    attributes:
      label: Workshop Suitability
      options:
        - label: This could be a good workshop issue for learning
        - label: This would help demonstrate GitHub Copilot Agent capabilities

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information, mockups, or examples
      placeholder: Add any other context, screenshots, or examples...
